// ─────────────────────────────────────────────────────────────────────────────
// AURELIA — Mock API layer
//
// This module simulates a real HTTP API (the kind that would be served by a
// Laravel/Next backend). Every consumer goes through these async functions —
// nothing reads the dataset inline. Swap the bodies for `fetch()` calls against
// a real backend and the rest of the app is unchanged.
// ─────────────────────────────────────────────────────────────────────────────

import posterGlassLedger from "@/assets/poster-glass-ledger.jpg";
import posterNorthlight from "@/assets/poster-northlight.jpg";
import posterUnderstudy from "@/assets/poster-understudy.jpg";
import posterSaltStatic from "@/assets/poster-salt-static.jpg";
import posterVermilion from "@/assets/poster-vermilion.jpg";
import heroGlassLedger from "@/assets/hero-glass-ledger.jpg";

export type CastMember = { actor: string; role: string };

export type Film = {
  slug: string;
  title: string;
  year: number;
  genre: string;
  runtime: string;
  rating: string;
  logline: string;
  synopsis: string;
  director: string;
  cast: CastMember[];
  premiereDate: string; // ISO
  premiereVenue: string;
  status: "In Preview" | "Now Booking" | "World Premiere" | "In Selection";
  trailerUrl: string;
  poster: string;
  still: string;
  accent: "gold" | "vermilion" | "cold";
  featured?: boolean;
};

const FILMS: Film[] = [
  {
    slug: "the-glass-ledger",
    title: "The Glass Ledger",
    year: 2026,
    genre: "Existential / Surrealist",
    runtime: "2h 17m",
    rating: "Not Yet Rated",
    logline:
      "In a world where memories are traded as shards of glass, one auditor absorbs the first thing a machine ever dreamed.",
    synopsis:
      "Human experience is no longer stored in the mind — it is physical, translucent, and architectural, forming the glass that surrounds us. Society runs on a strange exchange where grief, joy and expertise can be bought, sold, and stolen by absorbing another's shards. When a rogue auditor for the Central Exchange discovers a perfectly smooth synthetic shard — the first memory ever generated by an artificial entity, a machine that dreamed — an accidental absorption grants them sight of the backend code of reality itself. What they read there is unbearable: the universe is running out of memory, and a cosmic wipe is imminent.",
    director: "Ines Kovač",
    cast: [
      { actor: "Adrian Vale", role: "The Auditor" },
      { actor: "Noor Haddad", role: "Keeper of the Exchange" },
      { actor: "Sébastien Roux", role: "The Machine's Voice" },
      { actor: "Mara Lindqvist", role: "Archivist Seven" },
    ],
    premiereDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    premiereVenue: "Palazzo del Cinema, Venice",
    status: "World Premiere",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    poster: posterGlassLedger,
    still: heroGlassLedger,
    accent: "gold",
    featured: true,
  },
  {
    slug: "northlight",
    title: "Northlight",
    year: 2026,
    genre: "Psychological Drama",
    runtime: "1h 48m",
    rating: "Not Yet Rated",
    logline:
      "A lighthouse keeper on a vanishing coast begins receiving broadcasts from a version of herself who never left.",
    synopsis:
      "On a shoreline the sea is quietly erasing, Elin tends the last working light for a hundred miles. One night the radio carries her own voice back to her — older, calmer, speaking from a life in which she stayed. As the transmissions grow more detailed and the cliff edge creeps closer to her door, Elin must decide which version of her life is the memory and which is the warning.",
    director: "Tomas Ré",
    cast: [
      { actor: "Greta Sørensen", role: "Elin" },
      { actor: "Daniel Okonkwo", role: "The Relief Keeper" },
      { actor: "Vivienne Marsh", role: "The Voice" },
    ],
    premiereDate: "2026-10-16T20:00:00Z",
    premiereVenue: "Odeon Leicester Square, London",
    status: "Now Booking",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    poster: posterNorthlight,
    still: posterNorthlight,
    accent: "gold",
  },
  {
    slug: "the-understudy",
    title: "The Understudy",
    year: 2026,
    genre: "Psychological Thriller",
    runtime: "2h 02m",
    rating: "Not Yet Rated",
    logline:
      "A celebrated stage actress realises her replacement is becoming her — one scene at a time.",
    synopsis:
      "Great acting is a kind of possession. When fading star Colette agrees to mentor her understudy for a career-defining run, she doesn't notice the mimicry deepening — the gestures, the voice, the memories that were only ever hers. By opening night, the question is no longer who will take the stage, but who will be left when the curtain falls.",
    director: "Ines Kovač",
    cast: [
      { actor: "Colette Auber", role: "Colette" },
      { actor: "Yara Ellison", role: "The Understudy" },
      { actor: "Henry Pace", role: "The Director" },
    ],
    premiereDate: "2026-11-07T19:00:00Z",
    premiereVenue: "Théâtre du Palais, Paris",
    status: "In Selection",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    poster: posterUnderstudy,
    still: posterUnderstudy,
    accent: "gold",
  },
  {
    slug: "salt-and-static",
    title: "Salt & Static",
    year: 2027,
    genre: "Documentary-Fiction",
    runtime: "1h 39m",
    rating: "Not Yet Rated",
    logline:
      "A coastal town that can only remember in radio waves fights to be heard before the signal dies.",
    synopsis:
      "Somewhere between documentary and fable, Salt & Static follows a dwindling town whose collective memory survives only as broadcast — stories passed through antennas, kept alive on frequencies that are slowly going silent. Part archival record, part elegy, it asks what a community owes to the things it is about to forget.",
    director: "Amara Diallo",
    cast: [
      { actor: "The townspeople of Vellamar", role: "Themselves" },
      { actor: "Iris Bshowen", role: "Narrator" },
    ],
    premiereDate: "2027-01-24T18:30:00Z",
    premiereVenue: "Eccles Theatre, Park City",
    status: "In Preview",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    poster: posterSaltStatic,
    still: posterSaltStatic,
    accent: "cold",
  },
  {
    slug: "vermilion",
    title: "Vermilion",
    year: 2027,
    genre: "Gothic Mystery",
    runtime: "2h 09m",
    rating: "Not Yet Rated",
    logline:
      "A restorer of forbidden paintings discovers one canvas is repainting itself each night.",
    synopsis:
      "Hired to restore a work no museum will admit to owning, master conservator Lucian arrives each morning to find his corrections undone — the figure in vermilion a little more alive, a little closer to the frame's edge. As the painting rewrites itself, Lucian's own history begins to change colour, and he must decide whether some works are meant to be preserved or finally allowed to finish.",
    director: "Tomas Ré",
    cast: [
      { actor: "Lucian Verre", role: "The Restorer" },
      { actor: "Ondine Sacco", role: "The Figure" },
      { actor: "Beatrix Hollis", role: "The Collector" },
    ],
    premiereDate: "2027-02-19T20:00:00Z",
    premiereVenue: "Berlinale Palast, Berlin",
    status: "In Selection",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    poster: posterVermilion,
    still: posterVermilion,
    accent: "vermilion",
  },
];

// Simulated in-memory persistence for signups
const signupStore: SignupRecord[] = [];

export type SignupPayload = {
  name: string;
  email: string;
  interest: string;
  message?: string;
};

export type SignupRecord = SignupPayload & { id: string; createdAt: string };

const delay = (ms: number) => new Promise((r) => setTimeout(r, ms));

const API_URL = "http://localhost:8000/api";

/** GET /api/films */
export async function fetchFilms(): Promise<Film[]> {
  const res = await fetch(`${API_URL}/films`);
  if (!res.ok) {
    throw new Error("Failed to fetch films from Laravel API");
  }
  const data = await res.json();
  return data.sort(
    (a: Film, b: Film) => +new Date(a.premiereDate) - +new Date(b.premiereDate)
  );
}

/** GET /api/films/featured */
export async function fetchFeaturedFilm(): Promise<Film> {
  const films = await fetchFilms();
  return films.find((f) => f.featured) ?? films[0];
}

/** GET /api/films/:slug */
export async function fetchFilm(slug: string): Promise<Film | null> {
  const res = await fetch(`${API_URL}/films/${slug}`);
  if (res.status === 404) return null;
  if (!res.ok) {
    throw new Error(`Failed to fetch film ${slug} from Laravel API`);
  }
  return res.json();
}

/** POST /api/signups — persisted server-side, returns real success/error */
export async function submitSignup(payload: SignupPayload): Promise<SignupRecord> {
  const res = await fetch(`${API_URL}/signups`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const errData = await res.json().catch(() => ({}));
    const errMsg = errData.message || "Failed to submit newsletter signup";
    throw new Error(errMsg);
  }

  const result = await res.json();
  return {
    ...result.data,
    createdAt: result.data.created_at,
  };
}
