<?php

namespace Database\Seeders;

use App\Models\Film;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        Film::create([
            'slug' => 'the-glass-ledger',
            'title' => 'The Glass Ledger',
            'year' => 2026,
            'genre' => 'Existential / Surrealist',
            'runtime' => '2h 17m',
            'rating' => 'Not Yet Rated',
            'logline' => 'In a world where memories are traded as shards of glass, one auditor absorbs the first thing a machine ever dreamed.',
            'synopsis' => "Human experience is no longer stored in the mind — it is physical, translucent, and architectural, forming the glass that surrounds us. Society runs on a strange exchange where grief, joy and expertise can be bought, sold, and stolen by absorbing another's shards. When a rogue auditor for the Central Exchange discovers a perfectly smooth synthetic shard — the first memory ever generated by an artificial entity, a machine that dreamed — an accidental absorption grants them sight of the backend code of reality itself. What they read there is unbearable: the universe is running out of memory, and a cosmic wipe is imminent.",
            'director' => 'Ines Kovač',
            'cast' => [
                ['actor' => 'Adrian Vale', 'role' => 'The Auditor'],
                ['actor' => 'Noor Haddad', 'role' => 'Keeper of the Exchange'],
                ['actor' => 'Sébastien Roux', 'role' => "The Machine's Voice"],
                ['actor' => 'Mara Lindqvist', 'role' => 'Archivist Seven'],
            ],
            'premiereDate' => date('Y-m-d\TH:i:s\Z', strtotime('+20 days')),
            'premiereVenue' => 'Palazzo del Cinema, Venice',
            'status' => 'World Premiere',
            'trailerUrl' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            'poster' => '/assets/poster-glass-ledger.jpg',
            'still' => '/assets/hero-glass-ledger.jpg',
            'accent' => 'gold',
            'featured' => true,
        ]);

        Film::create([
            'slug' => 'northlight',
            'title' => 'Northlight',
            'year' => 2026,
            'genre' => 'Psychological Drama',
            'runtime' => '1h 48m',
            'rating' => 'Not Yet Rated',
            'logline' => 'A lighthouse keeper on a vanishing coast begins receiving broadcasts from a version of herself who never left.',
            'synopsis' => 'On a shoreline the sea is quietly erasing, Elin tends the last working light for a hundred miles. One night the radio carries her own voice back to her — older, calmer, speaking from a life in which she stayed. As the transmissions grow more detailed and the cliff edge creeps closer to her door, Elin must decide which version of her life is the memory and which is the warning.',
            'director' => 'Tomas Ré',
            'cast' => [
                ['actor' => 'Greta Sørensen', 'role' => 'Elin'],
                ['actor' => 'Daniel Okonkwo', 'role' => 'The Relief Keeper'],
                ['actor' => 'Vivienne Marsh', 'role' => 'The Voice'],
            ],
            'premiereDate' => '2026-10-16T20:00:00Z',
            'premiereVenue' => 'Odeon Leicester Square, London',
            'status' => 'Now Booking',
            'trailerUrl' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            'poster' => '/assets/poster-northlight.jpg',
            'still' => '/assets/poster-northlight.jpg',
            'accent' => 'gold',
            'featured' => false,
        ]);

        Film::create([
            'slug' => 'the-understudy',
            'title' => 'The Understudy',
            'year' => 2026,
            'genre' => 'Psychological Thriller',
            'runtime' => '2h 02m',
            'rating' => 'Not Yet Rated',
            'logline' => 'A celebrated stage actress realises her replacement is becoming her — one scene at a time.',
            'synopsis' => "Great acting is a kind of possession. When fading star Colette agrees to mentor her understudy for a career-defining run, she doesn't notice the mimicry deepening — the gestures, the voice, the memories that were only ever hers. By opening night, the question is no longer who will take the stage, but who will be left when the curtain falls.",
            'director' => 'Ines Kovač',
            'cast' => [
                ['actor' => 'Colette Auber', 'role' => 'Colette'],
                ['actor' => 'Yara Ellison', 'role' => 'The Understudy'],
                ['actor' => 'Henry Pace', 'role' => 'The Director'],
            ],
            'premiereDate' => '2026-11-07T19:00:00Z',
            'premiereVenue' => 'Théâtre du Palais, Paris',
            'status' => 'In Selection',
            'trailerUrl' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            'poster' => '/assets/poster-understudy.jpg',
            'still' => '/assets/poster-understudy.jpg',
            'accent' => 'gold',
            'featured' => false,
        ]);

        Film::create([
            'slug' => 'salt-and-static',
            'title' => 'Salt & Static',
            'year' => 2027,
            'genre' => 'Documentary-Fiction',
            'runtime' => '1h 39m',
            'rating' => 'Not Yet Rated',
            'logline' => 'A coastal town that can only remember in radio waves fights to be heard before the signal dies.',
            'synopsis' => 'Somewhere between documentary and fable, Salt & Static follows a dwindling town whose collective memory survives only as broadcast — stories passed through antennas, kept alive on frequencies that are slowly going silent. Part archival record, part elegy, it asks what a community owes to the things it is about to forget.',
            'director' => 'Amara Diallo',
            'cast' => [
                ['actor' => 'The townspeople of Vellamar', 'role' => 'Themselves'],
                ['actor' => 'Iris Bshowen', 'role' => 'Narrator'],
            ],
            'premiereDate' => '2027-01-24T18:30:00Z',
            'premiereVenue' => 'Eccles Theatre, Park City',
            'status' => 'In Preview',
            'trailerUrl' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            'poster' => '/assets/poster-salt-static.jpg',
            'still' => '/assets/poster-salt-static.jpg',
            'accent' => 'cold',
            'featured' => false,
        ]);

        Film::create([
            'slug' => 'vermilion',
            'title' => 'Vermilion',
            'year' => 2027,
            'genre' => 'Gothic Mystery',
            'runtime' => '2h 09m',
            'rating' => 'Not Yet Rated',
            'logline' => 'A restorer of forbidden paintings discovers one canvas is repainting itself each night.',
            'synopsis' => "Hired to restore a work no museum will admit to owning, master conservator Lucian arrives each morning to find his corrections undone — the figure in vermilion a little more alive, a little closer to the frame's edge. As the painting rewrites itself, Lucian's own history begins to change colour, and he must decide whether some works are meant to be preserved or finally allowed to finish.",
            'director' => 'Tomas Ré',
            'cast' => [
                ['actor' => 'Lucian Verre', 'role' => 'The Restorer'],
                ['actor' => 'Ondine Sacco', 'role' => 'The Figure'],
                ['actor' => 'Beatrix Hollis', 'role' => 'The Collector'],
            ],
            'premiereDate' => '2027-02-19T20:00:00Z',
            'premiereVenue' => 'Berlinale Palast, Berlin',
            'status' => 'In Selection',
            'trailerUrl' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            'poster' => '/assets/poster-vermilion.jpg',
            'still' => '/assets/poster-vermilion.jpg',
            'accent' => 'vermilion',
            'featured' => false,
        ]);
    }
}
