/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaunchesIndexRouteImport } from './routes/launches.index'
import { Route as LaunchesSlugRouteImport } from './routes/launches.$slug'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesIndexRoute = LaunchesIndexRouteImport.update({
  id: '/launches/',
  path: '/launches/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesSlugRoute = LaunchesSlugRouteImport.update({
  id: '/launches/$slug',
  path: '/launches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/launches/$slug': typeof LaunchesSlugRoute
  '/launches/': typeof LaunchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/launches/$slug': typeof LaunchesSlugRoute
  '/launches': typeof LaunchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/launches/$slug': typeof LaunchesSlugRoute
  '/launches/': typeof LaunchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/company' | '/contact' | '/launches/$slug' | '/launches/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/company' | '/contact' | '/launches/$slug' | '/launches'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/contact'
    | '/launches/$slug'
    | '/launches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  LaunchesSlugRoute: typeof LaunchesSlugRoute
  LaunchesIndexRoute: typeof LaunchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches/': {
      id: '/launches/'
      path: '/launches'
      fullPath: '/launches/'
      preLoaderRoute: typeof LaunchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches/$slug': {
      id: '/launches/$slug'
      path: '/launches/$slug'
      fullPath: '/launches/$slug'
      preLoaderRoute: typeof LaunchesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  LaunchesSlugRoute: LaunchesSlugRoute,
  LaunchesIndexRoute: LaunchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
