[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_sqlite", "php83Extensions.sqlite3", "php83Extensions.mbstring", "php83Extensions.openssl", "php83Extensions.tokenizer", "php83Extensions.xml", "php83Extensions.ctype", "php83Extensions.curl", "php83Extensions.fileinfo", "php83Extensions.bcmath", "composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "php artisan config:cache",
  "php artisan route:cache",
]

[start]
cmd = "php artisan migrate:fresh --seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
